apiVersion: apps/v1
kind: Deployment
metadata:
  name: poolwatch
  namespace: {{ .Values.namespace }}
  labels:
    app: poolwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poolwatch
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: poolwatch
    spec:
      containers:
      - image: {{ .Values.poolwatch.image }}
        name: poolwatch
        env:
        - name: MONGOURL
          value: {{ .Values.poolwatch.database }}