apiVersion: apps/v1
kind: Deployment
metadata:
  name: poolwatch
  namespace: {{ .Values.namespace }}
  labels:
    app: poolwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poolwatch
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: poolwatch
    spec:
      hostAliases:
      - ip: "173.194.217.109"
        hostnames:
        - "smtp.gmail.com"
        - "smtp.gmail.com.lan"
      containers:
      - image: {{ .Values.poolwatch.image }}
        name: poolwatch
        env:
        - name: MONGOURL
          value: {{ .Values.poolwatch.database }}
        - name: EMAILPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.emailSecret }}
              key: EMAILPASSWORD
        - name: EMAILSERVICE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.emailSecret }}
              key: EMAILSERVICE
        - name: EMAILUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.emailSecret }}
              key: EMAILUSERNAME