apiVersion: v1
kind: Service
metadata:
  name: poolwatch-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: poolwatch
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poolwatch-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: {{ .Values.poolwatch.hostname }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: poolwatch-service
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.poolwatch.hostname }}
    secretName: {{ .Values.poolwatch.tlsSecret }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: device-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: {{ .Values.poolwatch.deviceHostname }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: poolwatch-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-production-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongo-production
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017