apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: poolwatch
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      namespace: poolwatch
      labels:
        app: mongodb
    spec:
      containers:
      - image: docker.io/mongo:6
        name: mongodb