apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  namespace: poolwatch
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30000